### ISSUE TITLE
Implement LSD radix sort

### ISSUE THREAD

**Issue by rapus95** [JuliaCollections/SortingAlgorithms.jl#29]
if i want to sort by the first 2 characters using radix sort i use something like:
`sort(lines, alg=RadixSort, by=x->unsafe_load(Ptr{UInt16}(pointer(x))))`
but since you've implemented MSD only it doesn't deliver the needed result :/

**Comment by nalimilan** [comment]
Cc: @xiaodaigh

**Comment by rapus95** [comment]
coming from https://github.com/xiaodaigh/SortingLab.jl/issues/2

**Comment by xiaodaigh** [comment]
@rapus95 I think I might have missed a step, I guess you (like most of us) are on a little-endian machine so the code should be

```julia
sort(lines, alg=RadixSort, by=x->hton(unsafe_load(Ptr{UInt16}(pointer(x)))))
```
notice the additional `hton`because `unsafe_load` loads the bytes "back to front".

For future readers, the radixsort algorithm implemented is actually LSD.

**Comment by rapus95** [comment]
seems i won't be able to that after all thanks to a few UTF-8 strings... thus loading as UInt16 won't give the right result in comparison if the first character is not ascii for example...

Thanks for investigating nevertheless!!
Out of curiosity, would i have to use by=hton on my machine if i wanted to sort a Vector{Int} MSD?
