### ISSUE TITLE
There is another similar package: SortingLab.jl

### ISSUE THREAD

**Issue by skanskan** [JuliaCollections/SortingAlgorithms.jl#31]
There is another package similar to yours that provides radixsort on Julia.
https://github.com/xiaodaigh/SortingLab.jl
Maybe you could join forces.

**Comment by ararslan** [comment]
This package is pretty ancient and houses code that, if I remember correctly, used to be part of Julia itself but was moved out as non-essential functionality. Nonetheless this package is fairly widely used, so it seems worthwhile to me for improvements to the algorithms to be included here. @xiaodaigh, what are your thoughts?

**Comment by xiaodaigh** [comment]
Yeah good idea. Maybe just need to refresh PR #27 which I made 1 year ago. I now have more new code.

**Comment by skanskan** [comment]
Nice, this is a love story :)
