### ISSUE TITLE
Support sorting of `Vector{Union{T, Missing}}` for `RadixSort`

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaCollections/SortingAlgorithms.jl#34]
I think this can be done by adding and making some other accommodating changes

```
uint_mapping(Forward, missing) = 2^8sizeof(UInt)-1
uint_mapping(Reverse, missing) = UInt(0)
```

This is the approach taken in [SortingLab.jl](https://github.com/xiaodaigh/SortingLab.jl) to support sorting of `Vector{Union{Missing, T}}` for radix-sort.

**Comment by nalimilan** [comment]
Interesting. Could you make a PR? Probably also worth supporting `nothing`.

**Comment by xiaodaigh** [comment]
BTW

```julia
sort([nothing, 2,3])
```
returns an error on Julia 1.3. So should not support nothing in solidarity
