### ISSUE TITLE
Timeline for 1.0 release

### ISSUE THREAD

**Issue by bkamins** [JuliaCollections/SortingAlgorithms.jl#41]
Is there a timeline for 1.0 release of this package? Looking at the stability what we have here probably it is mature enough for this release.

CC @oxinabox (as I do not know whom to ping here)

**Comment by oxinabox** [comment]
Yeah this hasn't needed changes basically ever, except for julia releasing breaking changes.
AFAICT it has no maintainer because it is so complete it never has issues.

We could tag 1.0 release right now.
Except that itself would cause extra work for people to add compat.

**Comment by bkamins** [comment]
Yes - I just wanted to follow the https://discourse.julialang.org/t/getting-to-1-0-how-can-we-get-packages-to-make-that-tag/59608 discussion.

The problem is that with "Except that itself would cause extra work for people to add compat." there will be never a good moment to make this release :).

**Comment by oxinabox** [comment]
If noone objuects in the next week I will tag 1.0.

**Comment by bkamins** [comment]
OK. Thank you!

In DataFrames.jl then I will allow both 0.3 and 1 versions of SortingAlgorithms.jl in 1.0 release.

CC @nalimilan as you have some open PR here (proably non-blocking)

**Comment by nalimilan** [comment]
That's fine, my PRs are not breaking.

**Comment by oxinabox** [comment]
Done in https://github.com/JuliaCollections/SortingAlgorithms.jl/commit/aa2b98d384ddd132aae0219e68fb63b92513cb35

**Comment by Millak** [comment]
1.0.0 doesn't actually appear in the list of tags

**Comment by oxinabox** [comment]
Should show up sometime in next 24 hours. I have woken tagbot up
