### ISSUE TITLE
RadixSort error

### ISSUE THREAD

**Issue by 2005m** [JuliaCollections/SortingAlgorithms.jl#43]
Running Julia dev
```julia
using SortingAlgorithms
x=rand(10^8)
sort(x,alg=RadixSort);
ERROR: UndefVarError: nan2end! not defined
```
What is the overall fastest sorting algorithms you have in Julia? (Including multitreading)
Everything I have tested so far on large vector is 3 times slower than what I expect (and have).

**Comment by Ellipse0934** [comment]
Can you return the output for `versioninfo()` and `using Pkg; Pkg.status()` ?

**Comment by gitboy16** [comment]
I'll try to get you the exact informations when I can but I think I was running Julia 1.7 dev version on windows.

**Comment by 2005m** [comment]
I'll try to get you the exact version but I was running Julia 1.7 dev version on windows.

**Comment by 2005m** [comment]
We can close that now. Radix sort is fast but need to be parallelised. C++ `boost::sort::block_indirect_sort` is faster and parallelised. I have something twice faster for the same number of threads but did not publish it.
