### ISSUE TITLE
`Base.Sort.Float.nans2end!` removed in Julia 1.7

### ISSUE THREAD

**Issue by KristofferC** [JuliaCollections/SortingAlgorithms.jl#45]
Removed in https://github.com/JuliaLang/julia/pull/27817

Breaks:

https://github.com/JuliaCollections/SortingAlgorithms.jl/blob/aa2b98d384ddd132aae0219e68fb63b92513cb35/src/SortingAlgorithms.jl#L126

cc @nalimilan

**Comment by nalimilan** [comment]
See https://github.com/JuliaCollections/SortingAlgorithms.jl/pull/46.
