### ISSUE TITLE
RadixSort advertised as in place but is not.

### ISSUE THREAD

**Issue by LilithHafner** [JuliaCollections/SortingAlgorithms.jl#47]
Perhaps I'm missing something, but it feels like a contradiction to me that we [call RadixSort in place](https://github.com/JuliaCollections/SortingAlgorithms.jl/blob/master/README.md) and also allocate [`ts=similar(vs)`](https://github.com/JuliaCollections/SortingAlgorithms.jl/blob/67366a64d398de87e591419e1aa48e33d1ec2a9c/src/SortingAlgorithms.jl#L64) unless the caller provides a temporary array.

**Comment by Moelf** [comment]
also seeing this
```julia
julia> a = rand(Float32, 30, 1000, 1000);

julia> @btime sort!($a, dims = 1);
  352.697 ms (4956000 allocations: 182.43 MiB)

julia> using SortingAlgorithms

julia> @btime sort!($a, dims = 1, alg=RadixSort);
  10.968 s (13956000 allocations: 92.71 GiB)
```

**Comment by nalimilan** [comment]
Indeed, the input vector is modified in-place but a second vector of the same size is used. [Apparently](https://en.wikipedia.org/wiki/Radix_sort#Stable_MSD_radix_sort_implementations) this is required to get a stable algorithm. Let's remove this mention: https://github.com/JuliaCollections/SortingAlgorithms.jl/pull/49
