### ISSUE TITLE
Radix Sort Performance Issue (100x slower than Base)

### ISSUE THREAD

**Issue by LilithHafner** [JuliaCollections/SortingAlgorithms.jl#50]
I think this may have come up before, but I don't see an open issue, and I stumbled upon this bug again because it was the bottleneck when profiling some hypergraph generation codes that used StatseBase's `countmap` which uses SortingAlgorithms's `RadixSort`:
```julia
using SortingAlgorithms
x = [rand(1:10, 10) for i in 1:30000];
@elapsed sort.(x) # 0.015s
@elapsed sort.(x; alg=RadixSort) # 1.4s
```

**Comment by nalimilan** [comment]
Profiling reveals that a lot of time is spent on this line:
https://github.com/JuliaCollections/SortingAlgorithms.jl/blob/d0a900786aad792bca802600e0c98d592a1fa20e/src/SortingAlgorithms.jl#L76

This basically shows that radix sort currently isn't optimized at all for short vectors as it allocates a matrix of size 2048×6 for `Vector{Int}`. We could maybe adapt the algorithm depending on the input length, but an easy solution would be to fall back to `QuickSort` when the input is shorter than some threshold.
